services:
  traffic-monitor-app:
    build:
      context: .
      dockerfile: traffic-monitor-app/Dockerfile
    container_name: traffic-monitor-app
    ports:
      - "8080:8080"
      - "5001:5001/udp"
      - "5003:5003/udp"
    volumes:
      - ./config:/app/config:ro
    environment:
      TRAFFIC_TOOL_CONFIG: /app/config/traffic-tool.yml
    networks:
      - traffic-tool-net

  traffic-tester-app:
    ports:
      - "7001:7001/udp"
    build:
      context: .
      dockerfile: traffic-tester-app/Dockerfile
    container_name: traffic-tester-app
    depends_on:
      - traffic-monitor-app
    volumes:
      - ./config:/app/config:ro
    environment:
      TRAFFIC_TESTER_CONFIG: /app/config/tester-scenario.yml
    networks:
      - traffic-tool-net
    profiles:
      - tester
    restart: "no"

networks:
  traffic-tool-net:
    driver: bridge
