interfaces:
  - key: fruit
    name: Fruit Interface
    messages:
      - type: Orange
        definitionClass: com.example.schemas.fruit.OrangeMessageDefinition
      - type: Banana
        definitionClass: com.example.schemas.fruit.BananaMessageDefinition

  - key: weather
    name: Weather Interface
    messages:
      - type: TemperatureReading
        definitionClass: com.example.schemas.weather.TemperatureReadingMessageDefinition
