autoReply:
  enabled: false

interfaces:
  - key: fruit
    name: Fruit Interface
    messages:
      - type: Orange
        messageClass: com.example.schemas.fruit.OrangeMessage
        opcode: 1001
      - type: Banana
        messageClass: com.example.schemas.fruit.BananaMessage
        opcode: 1002
    autoReply:
      enabled: false
      host: localhost
      port: 7001

  - key: weather
    name: Weather Interface
    messages:
      - type: TemperatureReading
        messageClass: com.example.schemas.weather.TemperatureReadingMessage
        opcode: 2001
    autoReply:
      enabled: false
      host: localhost
      port: 7001

  - key: ping
    name: Ping Interface
    messages:
      - type: Ping
        messageClass: com.example.schemas.ping.PingMessage
        opcode: 3001
      - type: Pong
        messageClass: com.example.schemas.ping.PongMessage
        opcode: 3002
    autoReply:
      enabled: false
      host: localhost
      port: 7001

  - key: candy
    name: Candy Interface
    messages:
      - type: Candy
        messageClass: com.example.schemas.candy.CandyMessage
        opcode: 4001
    autoReply:
      enabled: false
      host: localhost
      port: 7001

  - key: rada
    name: Rada Interface
    protocol: UDP
    port: 5050
    byteOrder: BIG_ENDIAN
    headerType: com.example.schemas.rada.struct.RadaHeader
    opcodeFieldName: msgType
    messages:
      - type: RadaExtendedStatus
        messageClass: com.example.schemas.rada.messages.RadaExtendedStatus
        opcode: 1
      - type: RadaExtendedStatusMrs
        messageClass: com.example.schemas.rada.messages.RadaExtendedStatusMrs
        opcode: 2
      - type: RadaStatus
        messageClass: com.example.schemas.rada.messages.RadaStatus
        opcode: 3
      - type: RadaTracksExtended
        messageClass: com.example.schemas.rada.messages.RadaTracksExtended
        opcode: 4
    autoReply:
      enabled: false
