package com.example.tester.payload;

import com.example.schemacore.ProtocolHeaderCodec;
import com.example.schemacore.ReflectiveStructCodec;
import com.example.schemas.candy.CandyMessage;
import com.example.schemas.fruit.BananaMessage;
import com.example.schemas.fruit.FruitFreshness;
import com.example.schemas.fruit.OrangeMessage;
import com.example.schemas.ping.PingMessage;
import com.example.schemas.rada.messages.RadaStatus;
import com.example.schemas.weather.TemperatureReadingMessage;
import com.example.schemas.weather.WeatherCondition;
import com.example.schemacore.ProtocolMessage;
import com.example.tester.config.PayloadConfig;
import org.instancio.Instancio;

import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.Base64;

public class PayloadFactory {
    private static final int ORANGE_OPCODE = 1001;
    private static final int BANANA_OPCODE = 1002;
    private static final int TEMPERATURE_READING_OPCODE = 2001;
    private static final int PING_OPCODE = 3001;
    private static final int CANDY_OPCODE = 4001;
    private static final int RADA_STATUS_OPCODE = 3;

    public byte[] create(PayloadConfig config) {
        return switch (config.getMode()) {
            case TEXT -> config.getText().getBytes(StandardCharsets.UTF_8);
            case BASE64 -> Base64.getDecoder().decode(config.getBase64());
            case HEX -> parseHex(config.getHex());
            case FRUIT_ORANGE -> createFruitOrange(config);
            case FRUIT_BANANA -> createFruitBanana(config);
            case WEATHER_TEMPERATURE_READING -> createWeatherTemperatureReading(config);
            case PING -> createPing(config);
            case CANDY -> createCandy(config);
            case RADA_STATUS -> createRadaStatus();
        };
    }

    /**
     * Rada messages parse their own header as part of decoding themselves (see
     * {@link RadaStatus#fromByteArray}), so unlike the legacy envelope messages above, the
     * generated bytes already include the header - there's no separate {@code encodeMessage} wrap.
     * RadaStatus has no array fields, so it's safe to populate with Instancio's defaults.
     */
    private byte[] createRadaStatus() {
        RadaStatus message = Instancio.create(RadaStatus.class);
        message.getHeader().setMsgType(RADA_STATUS_OPCODE);
        return ReflectiveStructCodec.encode(message);
    }

    private byte[] createFruitOrange(PayloadConfig config) {
        OrangeMessage orangeMessage = new OrangeMessage(
                config.getFruit().getSourceFarm(),
                FruitFreshness.fromWireName(config.getFruit().getFreshness())
        );

        return encodeMessage(ORANGE_OPCODE, orangeMessage);
    }

    private byte[] createFruitBanana(PayloadConfig config) {
        BananaMessage bananaMessage = new BananaMessage(
                config.getFruit().getColor(),
                config.getFruit().getWeight()
        );

        return encodeMessage(BANANA_OPCODE, bananaMessage);
    }

    private byte[] createWeatherTemperatureReading(PayloadConfig config) {
        TemperatureReadingMessage message = new TemperatureReadingMessage(
                config.getWeather().getStationId(),
                config.getWeather().getTemperatureCelsius(),
                WeatherCondition.fromWireName(config.getWeather().getCondition())
        );

        return encodeMessage(TEMPERATURE_READING_OPCODE, message);
    }

    private byte[] createPing(PayloadConfig config) {
        PingMessage pingMessage = new PingMessage(config.getPing().getSequence());

        return encodeMessage(PING_OPCODE, pingMessage);
    }

    private byte[] createCandy(PayloadConfig config) {
        CandyMessage candyMessage = new CandyMessage(
                config.getCandy().getName(),
                config.getCandy().getCalories()
        );

        return encodeMessage(CANDY_OPCODE, candyMessage);
    }

    private byte[] encodeMessage(int opcode, ProtocolMessage message) {
        byte[] body = ReflectiveStructCodec.encode(message);
        return ProtocolHeaderCodec.encodeMessage(opcode, Instant.now().toEpochMilli(), body);
    }

    private byte[] parseHex(String hex) {
        String normalized = hex.replace(" ", "").replace("\n", "").replace("\t", "");

        if (normalized.length() % 2 != 0) {
            throw new IllegalArgumentException("HEX payload must contain an even number of characters");
        }

        byte[] bytes = new byte[normalized.length() / 2];

        for (int i = 0; i < normalized.length(); i += 2) {
            String pair = normalized.substring(i, i + 2);
            bytes[i / 2] = (byte) Integer.parseInt(pair, 16);
        }

        return bytes;
    }
}
